In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('C:/Users/Zhou/Desktop/DoD修改2209/DoD_删后.csv',index_col = 'Potential Period of Performance Start',parse_dates = ['Potential Period of Performance Start'])

In [3]:
df['num']=1

In [4]:
#df.head()

In [8]:
df_Quaterly = df['num'].resample('Q').count()

In [9]:
df_Quaterly

Potential Period of Performance Start
2010-09-30       1
2010-12-31       0
2011-03-31       0
2011-06-30       1
2011-09-30       1
2011-12-31       1
2012-03-31       2
2012-06-30       1
2012-09-30       1
2012-12-31       0
2013-03-31       0
2013-06-30       2
2013-09-30       2
2013-12-31       5
2014-03-31       3
2014-06-30       4
2014-09-30       8
2014-12-31      52
2015-03-31     290
2015-06-30     581
2015-09-30    1742
2015-12-31     370
2016-03-31     829
2016-06-30    1029
2016-09-30    1844
2016-12-31     242
2017-03-31     689
2017-06-30     666
2017-09-30    1580
2017-12-31     299
2018-03-31     496
2018-06-30     558
2018-09-30    1708
2018-12-31     137
2019-03-31     387
2019-06-30     582
2019-09-30    1172
2019-12-31     118
2020-03-31     253
2020-06-30     786
2020-09-30    1085
2020-12-31     107
2021-03-31     194
2021-06-30     213
2021-09-30       9
Freq: Q-DEC, Name: num, dtype: int64

In [10]:
res1.to_csv('时间分布.csv')

In [7]:
df_Quaterly

,Unnamed: 0,Award Number,关键词-中文,关键词-英文,Project Title,Award Abstract,Funding Agency Name（处理后）,Anticipated Award Amount,DoD Awarding Office（处理后）,Recipient Organization（处理后）,Recipient Organization（消歧后）,Last Name+First Name,PI Type,Potential Period of Performance End,时长,num
Potential Period of Performance Start,,,,,,,,,,,,,,,,
2010-09-30,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2010-12-31,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2011-03-31,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2011-06-30,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2011-09-30,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2011-12-31,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2012-03-31,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
2012-06-30,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2012-09-30,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2012-12-31,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2013-03-31,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2013-06-30,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
2013-09-30,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
2013-12-31,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
2014-03-31,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
2014-06-30,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
2014-09-30,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
2014-12-31,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52
2015-03-31,290,290,290,290,290,290,290,290,290,290,290,290,290,290,290,290
2015-06-30,581,581,581,581,581,581,581,581,581,581,581,581,581,581,581,581
2015-09-30,1742,1742,1741,1741,1742,1742,1742,1742,1742,1742,1742,1742,1742,1742,1742,1742
2015-12-31,370,370,369,369,370,370,370,370,370,370,370,370,370,370,370,370
2016-03-31,829,829,826,826,829,829,829,829,829,829,829,829,829,829,829,829
2016-06-30,1029,1029,1029,1029,1029,1029,1029,1029,1029,1029,1029,1029,1029,1029,1029,1029
2016-09-30,1844,1844,1843,1843,1844,1844,1844,1844,1844,1844,1844,1844,1844,1844,1844,1844
2016-12-31,242,242,242,242,242,242,242,242,242,242,242,242,242,242,242,242
2017-03-31,689,689,689,689,689,689,689,689,689,689,689,689,689,689,689,689
2017-06-30,666,666,666,666,666,666,666,666,666,666,666,666,666,666,666,666
2017-09-30,1580,1580,1574,1574,1580,1580,1580,1580,1580,1580,1580,1580,1580,1580,1580,1580
2017-12-31,299,299,298,298,299,299,299,299,299,299,299,299,299,299,299,299
2018-03-31,496,496,484,484,496,493,496,496,496,496,496,496,496,496,496,496
2018-06-30,558,558,558,558,558,558,558,558,558,558,558,558,558,558,558,558
2018-09-30,1708,1708,1690,1690,1708,1708,1708,1708,1708,1708,1708,1708,1708,1708,1708,1708
2018-12-31,137,137,137,137,137,137,137,137,137,137,137,137,137,137,137,137
2019-03-31,387,387,387,387,387,387,387,387,387,387,387,387,387,387,387,387
2019-06-30,582,582,582,582,582,582,582,582,582,582,582,582,582,582,582,582
2019-09-30,1172,1172,1167,1167,1172,1172,1172,1172,1172,1172,1172,1172,1172,1172,1172,1172
2019-12-31,118,118,118,118,118,118,118,118,118,118,118,118,118,118,118,118
2020-03-31,253,253,250,250,253,253,253,253,253,253,253,253,253,253,253,253
2020-06-30,786,786,786,786,786,786,786,786,786,786,786,786,786,786,786,786
2020-09-30,1085,1085,1083,1083,1085,1085,1085,1085,1085,1085,1085,1085,1085,1085,1085,1085
2020-12-31,107,107,107,107,107,107,107,107,107,107,107,107,107,107,107,107
2021-03-31,194,194,194,194,194,194,194,194,194,194,194,194,194,194,194,194
2021-06-30,213,213,213,213,213,213,213,213,213,213,213,213,213,213,213,213
2021-09-30,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9

#如何计算日期差
##这里不能把需要计算的日期值作为index

In [ ]:
#df = pd.read_csv('C:/Users/Zhou/Desktop/DoD修改2209/DoD.csv',parse_dates = ['Potential Period of Performance Start','Potential Period of Performance End'])
#df[len]=df['Potential Period of Performance End']-df['Potential Period of Performance Start']